import type { Metadata } from "next";
import { Philosopher, Artifika } from 'next/font/google';
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";

const philosopher = Philosopher({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--display-family',
});

const artifika = Artifika({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--text-family',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${philosopher.variable} ${artifika.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
